// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://totfspbyynugjkqcuvsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvdGZzcGJ5eW51Z2prcWN1dnN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODU3NDYsImV4cCI6MjA3MTM2MTc0Nn0.e9ENQS_RMei2moMImgr2pm05T1o4KIF133jMC9F85BI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});